#!/usr/bin/env python3
"""Generate the browser preview's data files from the project's sources of truth.

    layout.js  <- Tools/Editor/make_greybox_city.py (the same seeded greybox city as the Unreal map)
    tuning.js  <- FTraversalTuning in Source/WebOfTheCity/Public/Traversal/TraversalTypes.h
                  (every default, its group, its description and its editor clamp range)

Run after changing either source: python Web/Preview/gen_data.py
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "Tools" / "Editor"))

import make_greybox_city as city  # noqa: E402

FIELD = re.compile(
    r"/\*\*(?P<doc>.*?)\*/\s*"
    r"UPROPERTY\((?P<spec>[^)]*(?:\([^)]*\))?[^)]*)\)\s*"
    r"(?P<type>double|int32|bool)\s+(?P<name>\w+)\s*=\s*(?P<default>[^;]+);",
    re.S,
)


def tuning_fields():
    source = (ROOT / "Source/WebOfTheCity/Public/Traversal/TraversalTypes.h").read_text(encoding="utf-8")
    body = source[source.index("struct FTraversalTuning"):]
    body = body[: body.index("\n};")]
    fields = []
    for m in FIELD.finditer(body):
        spec = m.group("spec")
        group = re.search(r'Category\s*=\s*"Traversal\|(\w+)"', spec)
        lo = re.search(r'ClampMin\s*=\s*"([-\d.]+)"', spec)
        hi = re.search(r'ClampMax\s*=\s*"([-\d.]+)"', spec)
        raw = m.group("default").strip()
        kind = m.group("type")
        value = raw == "true" if kind == "bool" else (int(raw) if kind == "int32" else float(raw))
        fields.append({
            "name": m.group("name"),
            "type": {"double": "number", "int32": "int", "bool": "bool"}[kind],
            "default": value,
            "group": group.group(1) if group else "",
            "doc": " ".join(m.group("doc").split()),
            "min": float(lo.group(1)) if lo else None,
            "max": float(hi.group(1)) if hi else None,
        })
    return fields


def main():
    layout = city.make_layout()
    boxes = [[kind, round(c[0], 2), round(c[1], 2), round(c[2], 2), round(s[0], 2), round(s[1], 2), round(s[2], 2), int(a)]
             for kind, c, s, a in layout["boxes"]]
    data = {
        "seed": city.SEED,
        "extent": city.city_extent(),
        "park": city.park_bounds(),
        "grid": {"blockX": city.BLOCK_X_M, "blockY": city.BLOCK_Y_M, "avenue": city.AVENUE_M, "street": city.STREET_M,
                 "blocksX": city.BLOCKS_X, "blocksY": city.BLOCKS_Y},
        "boxes": boxes,
        "route": [[round(v, 2) for v in p] for p in layout["route"]],
        "stations": [[round(v, 2) for v in p] for p in layout["stations"]],
        "start": [round(v, 2) for v in layout["start"]],
    }
    header = "// Generated by Web/Preview/gen_data.py from Tools/Editor/make_greybox_city.py. Do not edit.\n"
    (HERE / "layout.js").write_text(header + "export const LAYOUT = " + json.dumps(data, separators=(",", ":")) + ";\n", encoding="utf-8")

    fields = tuning_fields()
    header = "// Generated by Web/Preview/gen_data.py from FTraversalTuning (TraversalTypes.h). Do not edit.\n"
    body = ("export const TUNING_FIELDS = " + json.dumps(fields, indent=1) + ";\n\n"
            "export function defaultTuning() {\n  const t = {};\n  for (const f of TUNING_FIELDS) t[f.name] = f.default;\n  return t;\n}\n")
    (HERE / "tuning.js").write_text(header + body, encoding="utf-8")
    print(f"layout.js: {len(boxes)} boxes, {len(data['route'])} route points; tuning.js: {len(fields)} settings")


if __name__ == "__main__":
    main()
