// Generated by Web/Preview/gen_data.py from FTraversalTuning (TraversalTypes.h). Do not edit.
export const TUNING_FIELDS = [
 {
  "name": "GroundRunSpeed",
  "type": "number",
  "default": 7.0,
  "group": "Ground",
  "doc": "Jog speed on the ground.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GroundSprintSpeed",
  "type": "number",
  "default": 14.0,
  "group": "Ground",
  "doc": "Sprint/parkour speed while holding the traversal button on the ground.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GroundJumpSpeed",
  "type": "number",
  "default": 9.0,
  "group": "Ground",
  "doc": "Upward speed of a jump (also used for coyote jumps).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GroundVaultMaxHeight",
  "type": "number",
  "default": 2.2,
  "group": "Ground",
  "doc": "Sprinting into an obstacle up to this tall auto-vaults over it; taller walls start a wall-run.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "Gravity",
  "type": "number",
  "default": 9.81,
  "group": "Air",
  "doc": "Real-world gravity; the per-state scales below multiply it.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AirGravityScale",
  "type": "number",
  "default": 1.6,
  "group": "Air",
  "doc": "Gravity multiplier while airborne (not swinging). Above 1 feels snappier than real life.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AirControlAccel",
  "type": "number",
  "default": 10.0,
  "group": "Air",
  "doc": "Sideways steering acceleration in the air. Can turn you, never speeds you past sprint speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AirMaxFallSpeed",
  "type": "number",
  "default": 60.0,
  "group": "Air",
  "doc": "Terminal fall speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AirCoyoteTime",
  "type": "number",
  "default": 0.15,
  "group": "Air",
  "doc": "After walking off a ledge, jump still works for this long.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AirJumpBufferTime",
  "type": "number",
  "default": 0.15,
  "group": "Air",
  "doc": "A jump press is remembered this long, so slightly early presses still count.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorReach",
  "type": "number",
  "default": 80.0,
  "group": "Anchor",
  "doc": "How far the web can reach.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorConeAngle",
  "type": "number",
  "default": 90.0,
  "group": "Anchor",
  "doc": "Full width of the search cone.",
  "min": 0.0,
  "max": 180.0
 },
 {
  "name": "AnchorConePitch",
  "type": "number",
  "default": 45.0,
  "group": "Anchor",
  "doc": "Cone centre, degrees above the horizon, when the camera is level.",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "AnchorCameraPitchInfluence",
  "type": "number",
  "default": 0.5,
  "group": "Anchor",
  "doc": "How much camera pitch tilts the cone (0 = ignore camera pitch, 1 = follow it fully).",
  "min": 0.0,
  "max": 1.0
 },
 {
  "name": "AnchorIdealElevationMin",
  "type": "number",
  "default": 35.0,
  "group": "Anchor",
  "doc": "Preferred anchor elevation band (Section 6.1: 35 to 55 degrees above the horizon).",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "AnchorIdealElevationMax",
  "type": "number",
  "default": 55.0,
  "group": "Anchor",
  "doc": "Upper end of the preferred elevation band.",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "AnchorMinElevation",
  "type": "number",
  "default": 15.0,
  "group": "Anchor",
  "doc": "Anchors lower than this are never used.",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "AnchorIdealDistance",
  "type": "number",
  "default": 40.0,
  "group": "Anchor",
  "doc": "Preferred distance to the anchor.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorSurfaceOffset",
  "type": "number",
  "default": 2.0,
  "group": "Anchor",
  "doc": "The swing pivots this far out from the wall, so arcs don't scrape the building.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorTraceRadius",
  "type": "number",
  "default": 0.3,
  "group": "Anchor",
  "doc": "Radius of the anchor search traces (thin geometry is easier to hit with a bigger value).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorSamplesYaw",
  "type": "int",
  "default": 7,
  "group": "Anchor",
  "doc": "Search rays across the cone. Cost is yaw x pitch traces per airborne frame.",
  "min": 1.0,
  "max": 15.0
 },
 {
  "name": "AnchorSamplesPitch",
  "type": "int",
  "default": 5,
  "group": "Anchor",
  "doc": "Search rays up the cone (elevation steps between the minimum elevation and the cone top).",
  "min": 1.0,
  "max": 9.0
 },
 {
  "name": "AnchorWeightElevation",
  "type": "number",
  "default": 1.0,
  "group": "Anchor",
  "doc": "Score weight for being in the ideal elevation band.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorWeightDistance",
  "type": "number",
  "default": 0.5,
  "group": "Anchor",
  "doc": "Score weight for being near the ideal distance.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorWeightAlignment",
  "type": "number",
  "default": 0.8,
  "group": "Anchor",
  "doc": "Score weight for being where the camera looks.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorPropBonus",
  "type": "number",
  "default": 0.3,
  "group": "Anchor",
  "doc": "Extra score for props tagged \"WebAnchor\" (water tanks, cranes, lampposts).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorHysteresis",
  "type": "number",
  "default": 0.15,
  "group": "Anchor",
  "doc": "Soft magnetism: extra score for staying on the previously previewed anchor, so the preview doesn't flicker.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorFacingPenalty",
  "type": "number",
  "default": 0.6,
  "group": "Anchor",
  "doc": "Score penalty for walls facing us head-on: swinging at them slams us into them.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AnchorHysteresisRadius",
  "type": "number",
  "default": 3.0,
  "group": "Anchor",
  "doc": "A candidate this close to the previous preview counts as \"the same anchor\" for the hysteresis bonus.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingGravityScale",
  "type": "number",
  "default": 2.0,
  "group": "Swing",
  "doc": "Gravity multiplier on the rope (Section 6.1: 1.5 to 2.5x).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingRopeMinLength",
  "type": "number",
  "default": 8.0,
  "group": "Swing",
  "doc": "Shortest rope; closer anchors are ignored.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingRopeMaxLength",
  "type": "number",
  "default": 80.0,
  "group": "Swing",
  "doc": "Longest rope; farther anchors are ignored.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingRopeReelSpeed",
  "type": "number",
  "default": 25.0,
  "group": "Swing",
  "doc": "How fast the rope shortens to keep the bottom of the arc off the street.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingPlaneAlign",
  "type": "number",
  "default": 0.85,
  "group": "Swing",
  "doc": "How far the swing pivot moves from the wall toward our line of travel (0 = pure physics, 1 = swing straight along our heading).",
  "min": 0.0,
  "max": 1.0
 },
 {
  "name": "SwingGroundClearance",
  "type": "number",
  "default": 6.0,
  "group": "Swing",
  "doc": "The lowest point of a swing stays at least this far above the ground below the anchor.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingLowPointAngle",
  "type": "number",
  "default": 35.0,
  "group": "Swing",
  "doc": "The low-point boost applies within this many degrees either side of the bottom of the arc.",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "SwingLowPointBoost",
  "type": "number",
  "default": 18.0,
  "group": "Swing",
  "doc": "Tangential acceleration through the low point, up to the current speed-tier cap.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingMinSpeed",
  "type": "number",
  "default": 12.0,
  "group": "Swing",
  "doc": "Speed floor on the rope: a swing never stalls.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingAirControl",
  "type": "number",
  "default": 8.0,
  "group": "Swing",
  "doc": "Steering acceleration while swinging.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingDamping",
  "type": "number",
  "default": 0.02,
  "group": "Swing",
  "doc": "Fraction of speed lost per second on the rope.",
  "min": 0.0,
  "max": 1.0
 },
 {
  "name": "SwingAutoReleaseAngle",
  "type": "number",
  "default": 65.0,
  "group": "Swing",
  "doc": "Past the low point, the web lets go by itself at this angle (or when you stop rising).",
  "min": 0.0,
  "max": 120.0
 },
 {
  "name": "SwingApexMinAngle",
  "type": "number",
  "default": 10.0,
  "group": "Swing",
  "doc": "Past this angle, the web also lets go as soon as you stop rising (top of the arc).",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "SwingReattachDelay",
  "type": "number",
  "default": 0.12,
  "group": "Swing",
  "doc": "While the button stays held, the next web fires this long after a release.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingAttachMaxRiseSpeed",
  "type": "number",
  "default": 3.0,
  "group": "Swing",
  "doc": "A new web only fires once you are rising slower than this, i.e. near the top of the arc. Webs fired while rising fast swing you backwards.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingMinAirTime",
  "type": "number",
  "default": 0.1,
  "group": "Swing",
  "doc": "After leaving the ground, the first web can fire after this long.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingChainWindow",
  "type": "number",
  "default": 1.5,
  "group": "Swing",
  "doc": "A swing that starts within this long of the last release counts as a chain.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SwingsPerTier",
  "type": "int",
  "default": 3,
  "group": "Swing",
  "doc": "Chained swings needed per speed tier.",
  "min": 1.0,
  "max": null
 },
 {
  "name": "PerfectReleaseChainBonus",
  "type": "int",
  "default": 1,
  "group": "Swing",
  "doc": "A well-timed release counts as this many extra chained swings.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SpeedTier1",
  "type": "number",
  "default": 25.0,
  "group": "Swing",
  "doc": "Speed cap at tier 1 (Section 6.1 starting values: about 25, 45, 70 m/s).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SpeedTier2",
  "type": "number",
  "default": 45.0,
  "group": "Swing",
  "doc": "Speed cap at tier 2.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SpeedTier3",
  "type": "number",
  "default": 70.0,
  "group": "Swing",
  "doc": "Speed cap at tier 3.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SpeedOverCapDrag",
  "type": "number",
  "default": 0.8,
  "group": "Swing",
  "doc": "Above the tier cap, this fraction of speed bleeds off per second (soft cap, not a wall).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ReleaseWindowMinAngle",
  "type": "number",
  "default": -5.0,
  "group": "Swing",
  "doc": "Perfect-release window start, degrees past the low point (negative = just before it).",
  "min": -90.0,
  "max": 90.0
 },
 {
  "name": "ReleaseWindowMaxAngle",
  "type": "number",
  "default": 35.0,
  "group": "Swing",
  "doc": "Perfect-release window end, degrees past the low point.",
  "min": -90.0,
  "max": 90.0
 },
 {
  "name": "ReleaseBoostSpeed",
  "type": "number",
  "default": 6.0,
  "group": "Swing",
  "doc": "Perfect-release boost along the direction of travel.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ReleaseBoostUp",
  "type": "number",
  "default": 2.0,
  "group": "Swing",
  "doc": "Perfect-release boost upwards (kept small: height comes from anchors, not boosts).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ReleaseJumpUp",
  "type": "number",
  "default": 8.0,
  "group": "Swing",
  "doc": "Pressing jump on the rope lets go with this much extra upward speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "bSkyAnchorEnabled",
  "type": "bool",
  "default": true,
  "group": "Fallbacks",
  "doc": "In wide-open spaces with nothing to hit, fire a limited \"sky anchor\".",
  "min": null,
  "max": null
 },
 {
  "name": "SkyAnchorDelay",
  "type": "number",
  "default": 0.25,
  "group": "Fallbacks",
  "doc": "Seconds of holding swing with no real anchor before a sky anchor fires.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SkyAnchorMaxInARow",
  "type": "int",
  "default": 2,
  "group": "Fallbacks",
  "doc": "Sky anchors allowed in a row. Swinging from a real surface, or touching down, refills them.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SkyAnchorHeight",
  "type": "number",
  "default": 30.0,
  "group": "Fallbacks",
  "doc": "Sky anchor height above you.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "SkyAnchorForward",
  "type": "number",
  "default": 25.0,
  "group": "Fallbacks",
  "doc": "Sky anchor distance ahead of you.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "bAutoWebCatch",
  "type": "bool",
  "default": true,
  "group": "Fallbacks",
  "doc": "Accessibility: fire a web automatically before hitting the street at speed.",
  "min": null,
  "max": null
 },
 {
  "name": "AutoWebCatchTime",
  "type": "number",
  "default": 0.7,
  "group": "Fallbacks",
  "doc": "Auto web-catch triggers when impact is this close (seconds)...",
  "min": 0.0,
  "max": null
 },
 {
  "name": "AutoWebCatchMinFallSpeed",
  "type": "number",
  "default": 15.0,
  "group": "Fallbacks",
  "doc": "...and you are falling at least this fast.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ZipRange",
  "type": "number",
  "default": 45.0,
  "group": "Zip",
  "doc": "Web-zip reach (jump button in the air).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ZipSpeed",
  "type": "number",
  "default": 60.0,
  "group": "Zip",
  "doc": "Zip travel speed; the duration is clamped to the min/max below (Section 6.1: 0.3 to 0.5 s).",
  "min": 1.0,
  "max": null
 },
 {
  "name": "ZipMinDuration",
  "type": "number",
  "default": 0.3,
  "group": "Zip",
  "doc": "Shortest zip.",
  "min": 0.05,
  "max": null
 },
 {
  "name": "ZipMaxDuration",
  "type": "number",
  "default": 0.5,
  "group": "Zip",
  "doc": "Longest zip.",
  "min": 0.05,
  "max": null
 },
 {
  "name": "ZipNoTargetDistance",
  "type": "number",
  "default": 20.0,
  "group": "Zip",
  "doc": "With nothing to zip to, you still dart this far in the camera direction.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ZipExitSpeed",
  "type": "number",
  "default": 14.0,
  "group": "Zip",
  "doc": "Speed carried out of a zip that didn't end on a surface.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ZipCooldown",
  "type": "number",
  "default": 0.2,
  "group": "Zip",
  "doc": "Minimum time between zips.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "ZipPerchClearance",
  "type": "number",
  "default": 0.15,
  "group": "Zip",
  "doc": "Zips to a perch arrive this far above it, so the approach clears the ledge lip.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "LaunchWindow",
  "type": "number",
  "default": 0.25,
  "group": "Zip",
  "doc": "Point-launch: press jump within this long of arriving on a perch (before or after).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "LaunchForwardSpeed",
  "type": "number",
  "default": 22.0,
  "group": "Zip",
  "doc": "Point-launch forward speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "LaunchUpSpeed",
  "type": "number",
  "default": 16.0,
  "group": "Zip",
  "doc": "Point-launch upward speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "LaunchStateTime",
  "type": "number",
  "default": 0.35,
  "group": "Zip",
  "doc": "How long the Launch state lasts before it becomes ordinary Air.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "WallRunSpeed",
  "type": "number",
  "default": 16.0,
  "group": "Wall",
  "doc": "Wall-run speed (traversal button held on a wall; runs up by default).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "WallCrawlSpeed",
  "type": "number",
  "default": 4.0,
  "group": "Wall",
  "doc": "Wall-crawl speed (button not held). No input = cling.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "WallAttachMinAngle",
  "type": "number",
  "default": 40.0,
  "group": "Wall",
  "doc": "Hitting a wall more head-on than this sticks to it; glancing hits just slide along.",
  "min": 0.0,
  "max": 90.0
 },
 {
  "name": "WallStickDistance",
  "type": "number",
  "default": 0.8,
  "group": "Wall",
  "doc": "How far past the body the wall probe looks to stay attached.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "WallJumpOutSpeed",
  "type": "number",
  "default": 10.0,
  "group": "Wall",
  "doc": "Jumping off a wall: speed away from it.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "WallJumpUpSpeed",
  "type": "number",
  "default": 9.0,
  "group": "Wall",
  "doc": "Jumping off a wall: upward speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "LedgeProbeHeight",
  "type": "number",
  "default": 1.2,
  "group": "Wall",
  "doc": "Height above the body centre of the \"is the wall still there\" head probe.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "LedgeSearchHeight",
  "type": "number",
  "default": 2.5,
  "group": "Wall",
  "doc": "How high above the probe a ledge top is searched for.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "VaultDuration",
  "type": "number",
  "default": 0.3,
  "group": "Wall",
  "doc": "Duration of the automatic mantle over a ledge.",
  "min": 0.05,
  "max": null
 },
 {
  "name": "VaultRiseFraction",
  "type": "number",
  "default": 0.6,
  "group": "Wall",
  "doc": "Share of the vault spent rising before moving over the edge.",
  "min": 0.05,
  "max": 0.95
 },
 {
  "name": "VaultExitSpeed",
  "type": "number",
  "default": 6.0,
  "group": "Wall",
  "doc": "Forward speed at the end of a vault.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "bGlideUnlocked",
  "type": "bool",
  "default": true,
  "group": "Glide",
  "doc": "Web-wings are unlocked (mid-game in the campaign; on for the prototype).",
  "min": null,
  "max": null
 },
 {
  "name": "GlideSpeed",
  "type": "number",
  "default": 24.0,
  "group": "Glide",
  "doc": "Target forward speed while gliding.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GlideAccel",
  "type": "number",
  "default": 12.0,
  "group": "Glide",
  "doc": "How fast glide speed and sink rate are reached.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GlideTurnRate",
  "type": "number",
  "default": 70.0,
  "group": "Glide",
  "doc": "Bank-turn rate, degrees per second.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GlideGravityScale",
  "type": "number",
  "default": 0.2,
  "group": "Glide",
  "doc": "Gravity multiplier while gliding.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "GlideSinkRate",
  "type": "number",
  "default": 4.0,
  "group": "Glide",
  "doc": "Maximum descent speed while gliding.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraFovBase",
  "type": "number",
  "default": 80.0,
  "group": "Camera",
  "doc": "Field of view at rest (Section 11: about 80).",
  "min": 40.0,
  "max": 140.0
 },
 {
  "name": "CameraFovMax",
  "type": "number",
  "default": 105.0,
  "group": "Camera",
  "doc": "Field of view at top speed (Section 11: 100 to 110).",
  "min": 40.0,
  "max": 140.0
 },
 {
  "name": "CameraFovSpeedStart",
  "type": "number",
  "default": 10.0,
  "group": "Camera",
  "doc": "FOV starts widening at this speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraFovSpeedFull",
  "type": "number",
  "default": 70.0,
  "group": "Camera",
  "doc": "FOV reaches the maximum at this speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraArmBase",
  "type": "number",
  "default": 3.5,
  "group": "Camera",
  "doc": "Camera distance behind the hero at rest.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraArmMax",
  "type": "number",
  "default": 5.5,
  "group": "Camera",
  "doc": "Camera distance behind the hero at top speed.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraLagSpeed",
  "type": "number",
  "default": 10.0,
  "group": "Camera",
  "doc": "Camera position lag (higher = tighter).",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraLookAhead",
  "type": "number",
  "default": 2.0,
  "group": "Camera",
  "doc": "At top speed the camera aims this far ahead along the velocity.",
  "min": 0.0,
  "max": null
 },
 {
  "name": "CameraMotionBlurMax",
  "type": "number",
  "default": 0.5,
  "group": "Camera",
  "doc": "Motion blur amount at top speed (0 at rest).",
  "min": 0.0,
  "max": 1.0
 },
 {
  "name": "CameraInterpSpeed",
  "type": "number",
  "default": 4.0,
  "group": "Camera",
  "doc": "How quickly FOV, arm length and look-ahead follow speed changes.",
  "min": 0.0,
  "max": null
 }
];

export function defaultTuning() {
  const t = {};
  for (const f of TUNING_FIELDS) t[f.name] = f.default;
  return t;
}
